#!/usr/bin/env python3

import sys
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import urllib
import time

# chromedriver_path = '/usr/bin/chromedriver'  # This line is not needed if using ChromeDriverManager
# driver = webdriver.Chrome(executable_path=chromedriver_path)

# Using ChromeDriverManager to automatically download and set up ChromeDriver

chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

# Create url variable containing the webpage for a Google image search.
# url = sys.argv[1]
url = ("https://www.google.com/search?q={s}&tbm=isch&tbs=sur%3Afc&hl=en&ved=0CAIQpwVqFwoTCKCa1c6s4-oCFQAAAAAdAAAAABAC&biw=1251&bih=568")
# Launch the browser and open the given url in the webdriver.
driver.get(url.format(s='Pets'))
# Scroll down the body of the web page and load the images.
driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
time.sleep(5)
# Find the images.
imgResults = driver.find_elements(By.XPATH,"//img[contains(@class,'img')]")
# Access and store the scr list of image url's.
src = []
for img in imgResults:
    src.append(img.get_attribute('src'))
# Retrieve and download the images.
for i in range(min(10, len(src))):    # Use min() to avoid IndexError if fewer than 10 images are found
    urllib.request.urlretrieve(str(src[i]), f"sample_data/pets{i}.jpg")
