#! /usr/bin/env python3

#https://www.geeksforgeeks.org/image-scraping-with-python/

import sys
import requests 
from bs4 import BeautifulSoup
from urllib.request import urlopen
from bs4 import BeautifulSoup


# Methode #1
print("Methode 1")


def getdata(url): 
    r = requests.get(url) 
    return r.text 
    
url = sys.argv[1]
htmldata = getdata(url) 
soup = BeautifulSoup(htmldata, 'html.parser') 
for item in soup.find_all('img'):
    print(item['src'])

# Methode #2
print("Methode 2")

htmldata = urlopen(url)
soup = BeautifulSoup(htmldata, 'html.parser')
images = soup.find_all('img')
  
for item in images:
    print(item['src'])
